<a href="https://colab.research.google.com/github/romisoleli/DataScience-Course/blob/main/Notebook5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
#Importar numpy
import numpy as np

In [ ]:
#1
array_12 = np.zeros(12, dtype=int)
print(array_12)

[0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
#2
array_10 = np.zeros(10)
array_10[4] = 10
print(array)


[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [ ]:
#3
array_1049= np.arange (10,50)
print (array_1049)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#4
array_4 = np.arange(9).reshape(3, 3)
print(array_4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#5
array_aleat = np.random.random(100)
print (array_aleat)
media = np.mean(array_5)
varianza = np.var(array_5)
print("Media:", media)
print("Varianza:", varianza)


[0.50624933 0.77446333 0.11210443 0.69705571 0.76818989 0.60307568
 0.93841676 0.26482931 0.27598963 0.37396341 0.45822669 0.8974631
 0.46499064 0.05363654 0.46165248 0.86156462 0.8970085  0.42993353
 0.30362345 0.04197877 0.69954959 0.54214711 0.37605204 0.79344032
 0.22968239 0.68042716 0.49102472 0.92327356 0.78092469 0.41732088
 0.67589051 0.44938145 0.88999389 0.85537476 0.4493363  0.04250811
 0.22022564 0.89593473 0.02515685 0.59866646 0.71100491 0.63845321
 0.02489064 0.68944798 0.9339832  0.67079735 0.81480548 0.56586194
 0.99976301 0.49564057 0.16757471 0.47237625 0.4805297  0.03126124
 0.34867097 0.24192176 0.07179055 0.68287062 0.809193   0.27126479
 0.55301732 0.11541642 0.35961142 0.99374371 0.08647373 0.98708884
 0.65715785 0.90400017 0.06745681 0.81429574 0.60265431 0.97219168
 0.88286018 0.49074354 0.47512819 0.99194708 0.53246538 0.29366697
 0.64427532 0.5128062  0.49510134 0.90325485 0.46834556 0.96208224
 0.06100658 0.07374235 0.03301465 0.79408883 0.81367787 0.67988

In [ ]:
#6
array_med = np.random.random(100)
media_sum = np.sum(array_med) / len(array_med)
print("Media calculada con np.sum:", media_sum)

Media calculada con np.sum: 0.492129816132734


In [ ]:
#7
array_aleat = np.random.random(100)
array_med= np.mean(array_aleat)
varianza_7 = np.sum((array_aleat - array_med) ** 2) / len(array_aleat)
print("Varianza calculada con np.sum:", varianza_7)

Varianza calculada con np.sum: 0.07344888484050696


In [ ]:
#8
array_aleat = np.random.random(20)
print(array_aleat)

[0.90194674 0.56110217 0.98435874 0.18671933 0.16291543 0.07137788
 0.73161959 0.59243932 0.93868748 0.58604758 0.05189455 0.05961803
 0.33784256 0.45414622 0.22308393 0.31192093 0.25674333 0.54359744
 0.9605097  0.89636966]
